[tool.black]
line-length = 88

[tool.ruff]
select = ["E", "F", "I001"]
ignore = ["E501"]
exclude = ["*/migrations/*", "scripts/*"]

[tool.isort]
profile = "black"
skip_glob = ["*/migrations/*", "scripts/*", "manage.py"]
