# Generated by Django 4.2.4 on 2023-09-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pss", "0005_auto_20230910_2245"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Territory",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=100, unique=True)),
                        ("label", models.CharField(max_length=10, unique=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                    ],
                ),
            ],
        )
    ]
