# Generated by Django 4.2.4 on 2023-09-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="territory",
            name="royalty_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="territory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
