# Generated by Django 4.2.4 on 2024-03-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_user_initials"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="arcgis_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("BDM", "Business development manager"),
                    ("BDA", "Business development administrator"),
                    ("SURVEYOR", "Surveyor"),
                    ("TECH", "Tech"),
                ],
                max_length=50,
            ),
        ),
    ]
