# Stage 1: build the executable
FROM golang:1.19 AS build

ARG SRC=lambdas/pricing_sheet

WORKDIR /code
ADD ${SRC} .
RUN go get -d
RUN go build -tags lambda.norpc -o ./main

# Stage 2: AWS Lambda image
FROM public.ecr.aws/lambda/provided:al2

COPY --from=build /code/main ./main
COPY --from=build /code/documents/templates ./templates

ENTRYPOINT ["./main"]
