FROM public.ecr.aws/lambda/python:3.10

ARG SRC=lambdas/arcgis_sync

# Install the Python dependencies
COPY ${SRC}/requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt

# Copy the function code
COPY ${SRC}/ ${LAMBDA_TASK_ROOT}

# Configure the handler
CMD ["app.handler"]
