# Generated by Django 4.2.4 on 2023-09-12 18:44

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_contact_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="extension",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone_number",
        ),
        migrations.CreateModel(
            name="ContactPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_type",
                    models.CharField(
                        choices=[("CELL", "Cell"), ("WORK", "Work")], max_length=10
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=25, validators=[core.validators.PhoneNumberValidator]
                    ),
                ),
                ("extension", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="customers.contact",
                    ),
                ),
            ],
        ),
    ]
