# Generated by Django 4.2.4 on 2023-09-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0003_remove_contact_extension_remove_contact_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
