# Generated by Django 4.2.4 on 2024-01-05 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")

    for customer in Customer.objects.all():
        project = customer.projects.order_by("id").last()

        if project:
            customer.territory = project.territory
            customer.business_development_manager = project.business_development_manager
            customer.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_territory_royalty_rate_territory_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0008_customer_segment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="business_development_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="territory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.territory",
            ),
        ),
        migrations.RunPython(forward),
    ]
