# Generated by Django 4.2.4 on 2023-09-10 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pss", "0004_alter_customer_state"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable("Territory", "core_territory"),
            ],
            state_operations=[
                migrations.DeleteModel("Territory"),
            ],
        ),
    ]
