name: Build/Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_standards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
      - name: Check code standards
        run: |
          make lint
          make check_fmt
